### ISSUE TITLE
Differences "resources": repo/website

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/resources#14]
I wonder about the difference between the website resources(http://designopen.org/resources/) and the resources repo (https://github.com/opensourcedesign/resources). It *seems* that the former is about open source design as an idea itself while the latter is, as it states, about "How to get street cred as a designer in open source projects." but content-wise there are significant similarities so I wonder if we could/should make it one.

**Comment by simonv3** [comment]
I would love some clarification here as well actually.

I'm sorry to be bikeshedding if I am, but I don't quite understand what the difference is between designopen and opensourcedesign, and what the different goals are, especially if the designopen folks are also the people doing this.

@jancborchardt @bnvk @una

**Comment by jdittrich** [comment]
I am relieved :-) I actually closed this again since I felt slightly stupid for I assumed it being the *same* thing 'till I looked closer.

**Comment by GarthDB** [comment]
I think there's a lot of overlap in a few areas, but not all. I would be open to combining the resources since there's solid overlap there, but our [current tool](https://chrome.google.com/webstore/detail/design-open/jahbclkpigpnoeamhgdilpdocgicnmml) is wonderful, and I'm not sure it would be best to relocate the page at this point. So I'd be most open to merging resources to Design Open.

On the job board, I'm not sure there is as much overlap at this point. Design Open's is more of a [project board](http://github.com/designopen/board) for OS projects looking for design contributions while Open Source Design's is a real job board with paid positions. We have different goals at this point, but further down the road there could be an opportunity to combine those as well.

The way I see it, the reason I think we are separate organizations is that we are catering to different audiences, which is reflected in the naming of the organizations. Open Source Design is concerned with only the design that has an open license or design for a project that has an F/OSS license.  Design Open on the other hand also includes people and projects that may not be open source, but are using open workflows/practices. For example, we encourage every designer to find ways to be open about their process, whether it be through the use of post mortems, collaborative open tools (like git/GitHub), journaling the process, sharing failed attempts, etc. I believe every designer has the ability to be more open in their process regardless of the type of client or work they do; even if it is for a closed corporation.

To move Design Open's work to Open Source Designers, would, I think, narrow its scope to only open source projects.

**Comment by jdittrich** [comment]
thanks!

**Comment by GarthDB** [comment]
Any feedback on my comment above @bnvk @simonv3 @jdittrich?

**Comment by jdittrich** [comment]
>So I'd be most open to merging resources to Design Open.

This would make sense to me.

**Comment by simonv3** [comment]
One of the main differences I noticed at the start was that the Open Source Design folks hang out on IRC while the Design Open folks seem to hang out on Slack (I'm going to call you out there, doesn't seem to be the most open method, though Slack is pretty cool, that's a tough one). Having now read how you differentiate yourself, and seen that difference reflected on your website, I get the difference a lot more.

One group is building a community of designers working on open source, while the other is focusing on building open workflows for designers. It may be a good idea to add this distinction to one of our websites, or our readmes. (On that note, I think Open Source Design needs a meta/ repo for stuff like this). 

I love the tool - though there seems to be a bit more gatekeeper action on the Design Open resources than on the Open Source Design resources, would you agree with that? How do resources make it on the list?

**Comment by bnvk** [comment]
Thanks for revisiting this @GarthDB I agree, Resources definitely seems like something we c/should merge together. This was actually the first thing @jancborchardt and I compiled towards the OSD effort. I really like your Resource adder widget BTW. However, @GarthDB mentioned the most interesting & concrete "differences" between both groups goals:

> Open Source Design is concerned with only the design that has an open license or design for a project that has an F/OSS license. Design Open on the other hand also includes people and projects that may not be open source, but are using open workflows/practices.

While, personally, ethically, and pragmatically I have nothing against designers who work on non-F/OSS licensed projects using F/OSS design resources- nor can anything be done about it- as the nature of F/OSS licenses allow for this re-appropriation and use of assets. 

I fully understand the notion of educating designers on the benefits of "open" workflows. But I wonder, does the @DesignOpen Resource list plan to include resources that are not actually opened licensed?

**Comment by jdittrich** [comment]
commenting on @simonv3’s comment:

**Communication Tools:** Using the chat tool of both groups, I think there are rationals for each one. Slack is not open, but comfortable, whereas IRC is open but at least I find it rather tedious to use from time to time (and I know many who probably get along slack, but not IRC well).
Ideally would be a tool that is easy to use, open and may even connect to established tools like IRC. 

 **Community Differences/Similarities**:

>It may be a good idea to add this distinction to one of our websites, or our readmes.

Good idea. Shall we create an issue for that in both projects? To have such info may actually help to connect the communities better and/or to enable people to find the one that suites them

**Comment by bnvk** [comment]
@jdittrich @simonv3 guys, I don't think the discussion about choice of chat tool pertains to this issue about Resources. I think that chat should be happening in [Chat #1](https://github.com/opensourcedesign/chat/issues/1), let's try to keep these threads on topic plz :wink:

**Comment by GarthDB** [comment]
@simonv3 - I agree with @bnvk on the irc/slack thing being a bit of a parallel issue, but we did have a good discussion on designopen's github issues https://github.com/DesignOpen/designopen.github.io/issues/195

> One group is building a community of designers working on open source, while the other is focusing on building open workflows for designers. It may be a good idea to add this distinction to one of our websites, or our readmes. (On that note, I think Open Source Design needs a meta/ repo for stuff like this).

I think you're close to spot on there. I would add that Design Open is not building tools for the sake of building tools, but to build a community of designers working towards more open practices. The difference between Design Open and Open Source Design's community is that we have found open source to be too exclusive. The irc is a good example, but not the only one and I think Guillermo Rauch did a great job hitting on this point in his [post about Slack and IRC](http://rauchg.com/slackin/):

>I registered the Socket.IO channel on Freenode right after I started the project. Even though it was super easy to start, we still had a major problem: onboarding new people to IRC.

>It’s hard to create a welcoming community around something fundamentally difficult to use. It lacks basic features like the ability to receive messages offline without setting up a server.

Everything we do is and will be open source, we will continue to encourage designers to open source their work wherever possible, and to prove that contributing design to existing open source projects is valuable to the community and the individual. At the same time, we will applaud designers for pushing for more open and transparent work within their non open source projects and organizations. We will go where the designers are, not just wait for them to realize the importance of this work on their own.

As far as the Resource Collector, it is just a tool to make things easier. It uses a bot to create a pull request to add the resource. It can be done manually as well if users prefer, and we made a bookmarklet for non chrome users. Here's an example [pull request](https://github.com/DesignOpen/designopen.github.io/pull/208) it generates.

**Comment by GarthDB** [comment]
and @simonv3 we are working to add the Slackin tool to make the slack channel more open and public. [![Join us on Slack!](https://osd-slackin.herokuapp.com/badge.svg)](https://osd-slackin.herokuapp.com)

**Comment by GarthDB** [comment]
@bnvk right now many of the resources are not just open source assets but also articles that are related to open and open source design.

I think you bring up a good point though, I think we could make it more clear. We should add a special category for assets and all of your sub categories.

We should also add a place to the type of license on those assets/projects. It would make it clearer for people looking for exact requirements.  I'll start talking to the resource collector team about it.

Once we implement that we can discuss the merging a bit more.

**Comment by simonv3** [comment]
@GarthDB @bnvk @jdittrich I certainly didn't mean to sidetrack the conversation being about Slack vs IRC, and I certainly didn't mean to bikeshed (thanks for the link to that issue).

This conversation has been super good in clarifying to me the roles the two groups play. I'm more satisfied knowing that there are actual different goals and directions in mind, rather than two groups trying to do the same thing separately.

I didn't realize the resource collector submitted PRs, for some reason I had it in my head that it went via issues. This even cooler.

**Comment by GarthDB** [comment]
@simonv3 the initial resource collector (mvp) did submit issues, but that was just another step in the process. It really slowed down the process, so @lauweijie switched it pull requests. He and @cmata23x3 have done some great work on it.

**Comment by GarthDB** [comment]
Here's how I currently see design and where I'd like it to be pushed:

![design](https://cloud.githubusercontent.com/assets/125516/6967497/ec18c04a-d91c-11e4-9632-4c559b178446.png)

**Comment by simonv3** [comment]
Closing this because I think this is fairly well settled. People can still link to it for future reference.
